[parameter]
[parameter.simple_update]
tau = 0.01
num_step = 1000

[parameter.full_update]
tau = 0.01
num_step = 1

[parameter.ctm]
iteration_max = 5
dimension = 16

[lattice]
type = "honeycomb lattice"
L = 2
W = 2
initial = "ferro"
virtual_dim = 4

[model]
type = "spin"
J0x = -1.0
J1y = -1.0
J2z = -1.0
