[parameter]
[parameter.general]
is_real = true

[parameter.simple_update]
num_step = 200
tau = 0.01

[parameter.full_update]
num_step = 0
tau = 0.01

[parameter.ctm]
iteration_max = 100
dimension = 10

[lattice]
type = "square lattice"
L = 3
W = 3
virtual_dim = 3
initial = "antiferro"

[model]
type = "spin"
J = 1.0
